### ISSUE TITLE
NeedUE5.1

### ISSUE THREAD

**Issue by JasonQWJ** [ultraleap/UnrealPlugin#116] opened 2022-11-29 14:19 UTC

**Comment by yiouyou** [comment] 2022-12-28 05:41
Same request!! As a ultraleap owner.

**Comment by larskendall** [comment] 2023-01-03 00:41
We're needing this as well. Ultraleap is no longer working in our builds with UE5.1.

Is there an estimate on when this will be fixed? And is there any workaround for the issue in the meantime?

**Comment by 2kah** [comment] 2023-01-03 12:57
Our next release is scheduled for the end of Jan, but there is a workaround! The issue is already fixed on the main branch (as of commit 15bbf4ee2cc44c05aab875db2771c1c37cb2cbf2) so you can clone or download the repo to get the fix.

**Comment by larskendall** [comment] 2023-01-04 11:59
@2kah Thanks so much for the quick response!

However, I'm still experiencing the same issue as of the commit you linked to (I just pulled latest)...

If I play using PIE everything works perfectly. But if I run in Standalone, or package a build of the game, Ultraleap functionality completely stops working.

I noticed an error related to Ultraleap in the logs after playing the packaged game. I've included the log file in case it helps.

[log.txt](https://github.com/ultraleap/UnrealPlugin/files/10343802/log.txt)

**Comment by Ultraleap-Dan** [comment] 2023-05-17 14:25
Hi @larskendall, please can you retest with the latest version of our hand tracking plugin for Unreal and let us know if this issue persists?

**Comment by Ultraleap-Dan** [comment] 2023-05-31 14:11
We will close this but please post a new issue if there are any further problems.

**Closed by Ultraleap-Dan** 2023-05-31 14:11 UTC

**Comment by larskendall** [comment] 2023-05-31 17:42
@Ultraleap-Dan I was able to test this just the other day and Ultraleap appeared to work perfectly in the build. Thank you!
